FROM ghcr.io/cross-rs/arm-unknown-linux-gnueabihf:main

ENV DEBIAN_FRONTEND=noninteractive

# Install newer GCC (10+) for C++20 support required by RocksDB
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
    apt-get update && \
    apt-get install -y \
        gcc-10 \
        g++-10 \
        gcc-10-arm-linux-gnueabihf \
        g++-10-arm-linux-gnueabihf \
        libclang-dev \
        clang \
        llvm \
        lld && \
    # Set GCC 10 as default for cross-compilation
    update-alternatives --install /usr/bin/arm-linux-gnueabihf-gcc arm-linux-gnueabihf-gcc /usr/bin/arm-linux-gnueabihf-gcc-10 100 && \
    update-alternatives --install /usr/bin/arm-linux-gnueabihf-g++ arm-linux-gnueabihf-g++ /usr/bin/arm-linux-gnueabihf-g++-10 100 && \
    # Clean up
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Verify GCC version
RUN arm-linux-gnueabihf-g++ --version
